# Generated by Django 3.2.5 on 2021-07-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_auto_20210714_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='depto',
            field=models.CharField(choices=[('CZ', 'Calzado'), ('RP', 'Ropa'), ('JG', 'Juguete'), ('CL', 'Coleccionable')], max_length=2, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='size_type',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('CH', 'Child'), ('PS', 'Preschool'), ('IF', 'Infant'), ('TD', 'Toddler')], max_length=2, verbose_name='Edad'),
        ),
    ]
