# Generated by Django 3.2.5 on 2021-07-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_auto_20210714_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='size_type',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('GS', 'Grade School'), ('PS', 'Preschool'), ('IF', 'Infant'), ('TD', 'Toddler')], max_length=2, verbose_name='Miembro'),
        ),
    ]
