# Generated by Django 3.2.5 on 2021-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_alter_mercancia_size_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='talla',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
