# Generated by Django 3.2.5 on 2021-07-26 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0007_alter_oferta_comprador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oferta',
            new_name='Oferta_compra',
        ),
        migrations.CreateModel(
            name='Oferta_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('talla', models.CharField(blank=True, max_length=5, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mercancia')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
