# Generated by Django 3.2.5 on 2021-08-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_auto_20210726_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_compra',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oferta_venta',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
