# Generated by Django 3.2.5 on 2021-08-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_auto_20210801_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_compra',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='oferta_venta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
