# Generated by Django 3.2.5 on 2021-08-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_auto_20210801_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_compra',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oferta_venta',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
