# Generated by Django 3.2.5 on 2021-08-16 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0011_auto_20210801_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas_compradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('talla', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha', models.DateTimeField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mercancia')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
