# Generated by Django 3.2.5 on 2021-08-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0014_auto_20210817_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas_compradas',
            name='comision_comprador',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertas_compradas',
            name='comision_vendedor',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
